### PR TITLE
add support for array payloads

### PR DESCRIPTION
**Pull request by anthonymzupancic**
# PR details

## What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Fix
- [ ] Improvements
- [x] New Feature
- [ ] Documentation updates
- [ ] Other, please explain:

## What changes did you make? (Give an overview)
Updated util.js to add support for Array payloads to pass validation.
...

### CODE REVIEW

**Comment by DougMidgley** [comment]
Hey,
I would rather see the Array.isArray(SOMEVAR HERE) method used, since it also covers this. If it is an Array, it isnt an object, so doenst make sense to extend this method directly since some cases do NEED an object.

**Comment by anthonymzupancic** [comment]
Updated PR

**Review by DougMidgley — CHANGES_REQUESTED** [review]
There is a bunch of indentation/formatting changes which dont seem to do anything? Did you setup the repo correctly when you made the changes? lemme know if you have questions on it :)

**Comment by anthonymzupancic** [comment]
@DougMidgley I had a formatter running on save, I've run eslint -fix and seem to have fixed the formatting issues. Let me know if that works or if I need to adjust anything else.

**Review by DougMidgley — APPROVED** [review]

**Comment by DougMidgley** [comment]
Super! thanks for that!

**Pull request closed without merging**
